name: Test
on: [push]
jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
            pip install -e
      - name: Run Tests
        run: python -m unittest tests/*.py
#        working-directory: ./tests